// React/calculator/src/components/navbar.jsx
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import $ from 'jquery';

class Navbar extends Component {
    state = {  } 

    render_calculator = () => {
        if (this.props.is_login) {
            return (
                <li className="nav-item">
                    <Link className="nav-link" to="/calculator/calculator">计算器</Link>
                </li>
            );
        } else {
            return "";
        }
    }

    handleClick = () => {
        $.ajax({
            url: "https://app165.acapp.acwing.com.cn/calculator/logout/",
            type: "get",
            success: resp => {
                if (resp.result === "success") {
                    // 成功，重定向
                    window.location.href = "/calculator";
                }
            }
        })
    }

    render_user = () => {
        if (this.props.is_login) {
            return (
                <ul className="navbar-nav">
                    <li className="nav-item">
                    <Link className="nav-link active" aria-current="page">{this.props.username}</Link>
                    </li>
                    <li className="nav-item">
                    <Link onClick={this.handleClick} className="nav-link">退出</Link>
                    </li>
                </ul>
            );
        } else {
            return (
                <ul className="navbar-nav">
                    <li className="nav-item">
                    <Link className="nav-link active" aria-current="page" to="/calculator/login">登录</Link>
                    </li>
                    <li className="nav-item">
                    <Link className="nav-link" to="/calculator/register">注册</Link>
                    </li>
                </ul>
            );
        }
    }

    render() { 
        return (
            <React.Fragment>
                <nav className="navbar navbar-expand-lg navbar-light bg-light">
                    <div className="container">
                        <Link className="navbar-brand" to="/calculator/">Web</Link>
                        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                        </button>
                        <div className="collapse navbar-collapse" id="navbarText">
                        <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                            <li className="nav-item">
                            <Link className="nav-link active" aria-current="page" to="/calculator/home">首页</Link>
                            </li>
                        {this.render_calculator()}
                        </ul>
                        {this.render_user()}
                        </div>
                    </div>
                </nav>
            </React.Fragment>
        );
    }
}
 
export default Navbar;

// Vue3/myspace/src/components/NavBar.vue
// html

<template>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <router-link class="navbar-brand" :to="{name: 'home'}">MySpace</router-link>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <router-link class="nav-link" :to="{name: 'home'}">首页</router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" :to="{name: 'userlist'}">好友列表</router-link>
        </li>
        <!-- <li class="nav-item">
          <router-link class="nav-link" :to="{name: 'userprofile', params: {userId: 2}}">好友动态</router-link>
        </li> -->
      </ul>
      <ul class="navbar-nav" v-if="!$store.state.user.is_login">
        <li class="nav-item">
          <router-link class="nav-link" :to="{name: 'login'}">登录</router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" :to="{name: 'register'}">注册</router-link>
        </li>
      </ul>
      <ul class="navbar-nav" v-else>
        <li class="nav-item">
          <router-link
             class="nav-link"
             :to="{name: 'userprofile', params: {userId: $store.state.user.id}}"
          >
            {{$store.state.user.username}}
          </router-link>
        </li>
        <li class="nav-item">
          <a @click="logout" class="nav-link" style="cursor: pointer">退出</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</template>

// js

<script>
import { useStore } from 'vuex';

export default {
    name: "NavBar",
    setup() {
      const store = useStore();
      const logout = () => {
        store.commit("logout");
      };

      return {
        logout,
      }
    }
}
</script>

// css, 加上scoped则不会影响其他组件

<style scoped>

</style>
